// SPDX-License-Identifier: MPL-2.0
// Ported from mailkit_arkts (user-owned; confirmed 2026-08-12). See ATTRIBUTIONS.md.

/// Code page 18: Settings.
pub(super) const SETTINGS_TOKENS: &[(u8, &str)] = &[
    (0x05, "Settings"),
    (0x06, "Status"),
    (0x07, "Get"),
    (0x08, "Set"),
    (0x09, "Oof"),
    (0x0A, "OofState"),
    (0x0B, "StartTime"),
    (0x0C, "EndTime"),
    (0x0D, "OofMessage"),
    (0x0E, "AppliesToInternal"),
    (0x0F, "AppliesToExternalKnown"),
    (0x10, "AppliesToExternalUnknown"),
    (0x11, "Enabled"),
    (0x12, "ReplyMessage"),
    (0x13, "BodyType"),
    (0x14, "DevicePassword"),
    (0x15, "Password"),
    (0x16, "DeviceInformation"),
    (0x17, "Model"),
    (0x18, "IMEI"),
    (0x19, "FriendlyName"),
    (0x1A, "OS"),
    (0x1B, "OSLanguage"),
    (0x1C, "PhoneNumber"),
    (0x1D, "UserInformation"),
    (0x1E, "EmailAddresses"),
    (0x1F, "SMTPAddress"),
    (0x20, "UserAgent"),
    (0x21, "EnableOutboundSMS"),
    (0x22, "MobileOperator"),
    (0x23, "PrimarySmtpAddress"),
    (0x24, "Accounts"),
    (0x25, "Account"),
    (0x26, "AccountId"),
    (0x27, "AccountName"),
    (0x28, "UserDisplayName"),
    (0x29, "SendDisabled"),
    (0x2B, "RightsManagementInformation"),
];

/// Code page 19: DocumentLibrary.
pub(super) const DOCS_TOKENS: &[(u8, &str)] = &[
    (0x05, "LinkId"),
    (0x06, "DisplayName"),
    (0x07, "IsFolder"),
    (0x08, "CreationDate"),
    (0x09, "LastModifiedDate"),
    (0x0A, "IsHidden"),
    (0x0B, "ContentLength"),
    (0x0C, "ContentType"),
];

/// Code page 20: ItemOperations.
pub(super) const ITEMS_TOKENS: &[(u8, &str)] = &[
    (0x05, "ItemOperations"),
    (0x06, "Fetch"),
    (0x07, "Store"),
    (0x08, "Options"),
    (0x09, "Range"),
    (0x0A, "Total"),
    (0x0B, "Properties"),
    (0x0C, "Data"),
    (0x0D, "Status"),
    (0x0E, "Response"),
    (0x0F, "Version"),
    (0x10, "Schema"),
    (0x11, "Part"),
    (0x12, "EmptyFolderContents"),
    (0x13, "DeleteSubFolders"),
    (0x14, "UserName"),
    (0x15, "Password"),
    (0x16, "Move"),
    (0x17, "DstFldId"),
    (0x18, "ConversationId"),
    (0x19, "MoveAlways"),
];

/// Code page 21: ComposeMail.
pub(super) const COMPOSE_TOKENS: &[(u8, &str)] = &[
    (0x05, "SendMail"),
    (0x06, "SmartForward"),
    (0x07, "SmartReply"),
    (0x08, "SaveInSentItems"),
    (0x09, "ReplaceMime"),
    (0x0B, "Source"),
    (0x0C, "FolderId"),
    (0x0D, "ItemId"),
    (0x0E, "LongId"),
    (0x0F, "InstanceId"),
    (0x10, "Mime"),
    (0x11, "ClientId"),
    (0x12, "Status"),
    (0x13, "AccountId"),
    (0x15, "Forwardees"),
    (0x16, "Forwardee"),
    (0x17, "ForwardeeName"),
    (0x18, "ForwardeeEmail"),
];

/// Code page 22: Email2.
pub(super) const EMAIL2_TOKENS: &[(u8, &str)] = &[
    (0x05, "UmCallerID"),
    (0x06, "UmUserNotes"),
    (0x07, "UmAttDuration"),
    (0x08, "UmAttOrder"),
    (0x09, "ConversationId"),
    (0x0A, "ConversationIndex"),
    (0x0B, "LastVerbExecuted"),
    (0x0C, "LastVerbExecutionTime"),
    (0x0D, "ReceivedAsBcc"),
    (0x0E, "Sender"),
    (0x0F, "CalendarType"),
    (0x10, "IsLeapMonth"),
    (0x11, "AccountId"),
    (0x12, "FirstDayOfWeek"),
    (0x13, "MeetingMessageType"),
    (0x15, "IsDraft"),
    (0x16, "Bcc"),
    (0x17, "Send"),
];

/// Code page 23: Notes.
pub(super) const NOTES_TOKENS: &[(u8, &str)] = &[
    (0x05, "Subject"),
    (0x06, "MessageClass"),
    (0x07, "LastModifiedDate"),
    (0x08, "Categories"),
    (0x09, "Category"),
];

/// Code page 24: RightsManagement.
pub(super) const RIGHTS_TOKENS: &[(u8, &str)] = &[
    (0x05, "RightsManagementSupport"),
    (0x06, "RightsManagementTemplates"),
    (0x07, "RightsManagementTemplate"),
    (0x08, "RightsManagementLicense"),
    (0x09, "EditAllowed"),
    (0x0A, "ReplyAllowed"),
    (0x0B, "ReplyAllAllowed"),
    (0x0C, "ForwardAllowed"),
    (0x0D, "ModifyRecipientsAllowed"),
    (0x0E, "ExtractAllowed"),
    (0x0F, "PrintAllowed"),
    (0x10, "ExportAllowed"),
    (0x11, "ProgrammaticAccessAllowed"),
    (0x12, "Owner"),
    (0x13, "ContentExpiryDate"),
    (0x14, "TemplateID"),
    (0x15, "TemplateName"),
    (0x16, "TemplateDescription"),
    (0x17, "ContentOwner"),
    (0x18, "RemoveRightsManagementProtection"),
];

/// Code page 25: Find.
pub(super) const FIND_TOKENS: &[(u8, &str)] = &[
    (0x05, "Find"),
    (0x06, "SearchId"),
    (0x07, "ExecuteSearch"),
    (0x08, "MailBoxSearchCriterion"),
    (0x09, "Query"),
    (0x0A, "Status"),
    (0x0B, "FreeText"),
    (0x0C, "Options"),
    (0x0D, "Range"),
    (0x0E, "DeepTraversal"),
    (0x11, "Response"),
    (0x12, "Result"),
    (0x13, "Properties"),
    (0x14, "Preview"),
    (0x15, "HasAttachments"),
    (0x16, "Total"),
    (0x17, "DisplayCc"),
    (0x18, "DisplayBcc"),
    (0x19, "GALSearchCriterion"),
    (0x20, "MaxPictures"),
    (0x21, "MaxSize"),
    (0x22, "Picture"),
];
