// SPDX-License-Identifier: MPL-2.0
// Ported from mailkit_arkts (user-owned; confirmed 2026-08-12). See ATTRIBUTIONS.md.

/// Code page 10: ResolveRecipients.
pub(super) const RECIPIENTS_TOKENS: &[(u8, &str)] = &[
    (0x05, "ResolveRecipients"),
    (0x06, "Response"),
    (0x07, "Status"),
    (0x08, "Type"),
    (0x09, "Recipient"),
    (0x0A, "DisplayName"),
    (0x0B, "EmailAddress"),
    (0x0C, "Certificates"),
    (0x0D, "Certificate"),
    (0x0E, "MiniCertificate"),
    (0x0F, "Options"),
    (0x10, "To"),
    (0x11, "CertificateRetrieval"),
    (0x12, "RecipientCount"),
    (0x13, "MaxCertificates"),
    (0x14, "MaxAmbiguousRecipients"),
    (0x15, "CertificateCount"),
    (0x16, "Availability"),
    (0x17, "StartTime"),
    (0x18, "EndTime"),
    (0x19, "MergedFreeBusy"),
    (0x1A, "Picture"),
    (0x1B, "MaxSize"),
    (0x1C, "Data"),
    (0x1D, "MaxPictures"),
];

/// Code page 11: ValidateCert.
pub(super) const VALIDATE_TOKENS: &[(u8, &str)] = &[
    (0x05, "ValidateCert"),
    (0x06, "Certificates"),
    (0x07, "Certificate"),
    (0x08, "CertificateChain"),
    (0x09, "CheckCrl"),
    (0x0A, "Status"),
];

/// Code page 12: Contacts2.
pub(super) const CONTACTS2_TOKENS: &[(u8, &str)] = &[
    (0x05, "CustomerId"),
    (0x06, "GovernmentId"),
    (0x07, "IMAddress"),
    (0x08, "IMAddress2"),
    (0x09, "IMAddress3"),
    (0x0A, "ManagerName"),
    (0x0B, "CompanyMainPhone"),
    (0x0C, "AccountName"),
    (0x0D, "NickName"),
    (0x0E, "MMS"),
];

/// Code page 13: Ping.
pub(super) const PING_TOKENS: &[(u8, &str)] = &[
    (0x05, "Ping"),
    (0x07, "Status"),
    (0x08, "HeartbeatInterval"),
    (0x09, "Folders"),
    (0x0A, "Folder"),
    (0x0B, "Id"),
    (0x0C, "Class"),
    (0x0D, "MaxFolders"),
];

/// Code page 14: Provision.
pub(super) const PROVISION_TOKENS: &[(u8, &str)] = &[
    (0x05, "Provision"),
    (0x06, "Policies"),
    (0x07, "Policy"),
    (0x08, "PolicyType"),
    (0x09, "PolicyKey"),
    (0x0A, "Data"),
    (0x0B, "Status"),
    (0x0C, "RemoteWipe"),
    (0x0D, "EASProvisionDoc"),
    (0x0E, "DevicePasswordEnabled"),
    (0x0F, "AlphanumericDevicePasswordRequired"),
    (0x10, "RequireStorageCardEncryption"),
    (0x11, "PasswordRecoveryEnabled"),
    (0x13, "AttachmentsEnabled"),
    (0x14, "MinDevicePasswordLength"),
    (0x15, "MaxInactivityTimeDeviceLock"),
    (0x16, "MaxDevicePasswordFailedAttempts"),
    (0x17, "MaxAttachmentSize"),
    (0x18, "AllowSimpleDevicePassword"),
    (0x19, "DevicePasswordExpiration"),
    (0x1A, "DevicePasswordHistory"),
    (0x1B, "AllowStorageCard"),
    (0x1C, "AllowCamera"),
    (0x1D, "RequireDeviceEncryption"),
    (0x1E, "AllowUnsignedApplications"),
    (0x1F, "AllowUnsignedInstallationPackages"),
    (0x20, "MinDevicePasswordComplexCharacters"),
    (0x21, "AllowWiFi"),
    (0x22, "AllowTextMessaging"),
    (0x23, "AllowPOPIMAPEmail"),
    (0x24, "AllowBluetooth"),
    (0x25, "AllowIrDA"),
    (0x26, "RequireManualSyncWhenRoaming"),
    (0x27, "AllowDesktopSync"),
    (0x28, "MaxCalendarAgeFilter"),
    (0x29, "AllowHTMLEmail"),
    (0x2A, "MaxEmailAgeFilter"),
    (0x2B, "MaxEmailBodyTruncationSize"),
    (0x2C, "MaxEmailHTMLBodyTruncationSize"),
    (0x2D, "RequireSignedSMIMEMessages"),
    (0x2E, "RequireEncryptedSMIMEMessages"),
    (0x2F, "RequireSignedSMIMEAlgorithm"),
    (0x30, "RequireEncryptionSMIMEAlgorithm"),
    (0x31, "AllowSMIMEEncryptionAlgorithmNegotiation"),
    (0x32, "AllowSMIMESoftCerts"),
    (0x33, "AllowBrowser"),
    (0x34, "AllowConsumerEmail"),
    (0x35, "AllowRemoteDesktop"),
    (0x36, "AllowInternetSharing"),
    (0x37, "UnapprovedInROMApplicationList"),
    (0x38, "ApplicationName"),
    (0x39, "ApprovedApplicationList"),
    (0x3A, "Hash"),
    (0x3B, "AccountOnlyRemoteWipe"),
];

/// Code page 15: Search.
pub(super) const SEARCH_TOKENS: &[(u8, &str)] = &[
    (0x05, "Search"),
    (0x07, "Store"),
    (0x08, "Name"),
    (0x09, "Query"),
    (0x0A, "Options"),
    (0x0B, "Range"),
    (0x0C, "Status"),
    (0x0D, "Response"),
    (0x0E, "Result"),
    (0x0F, "Properties"),
    (0x10, "Total"),
    (0x11, "EqualTo"),
    (0x12, "Value"),
    (0x13, "And"),
    (0x14, "Or"),
    (0x15, "FreeText"),
    (0x17, "DeepTraversal"),
    (0x18, "LongId"),
    (0x19, "RebuildResults"),
    (0x1A, "LessThan"),
    (0x1B, "GreaterThan"),
    (0x1E, "UserName"),
    (0x1F, "Password"),
    (0x20, "ConversationId"),
    (0x21, "Picture"),
    (0x22, "MaxSize"),
    (0x23, "MaxPictures"),
];

/// Code page 16: GAL.
pub(super) const GAL_TOKENS: &[(u8, &str)] = &[
    (0x05, "DisplayName"),
    (0x06, "Phone"),
    (0x07, "Office"),
    (0x08, "Title"),
    (0x09, "Company"),
    (0x0A, "Alias"),
    (0x0B, "FirstName"),
    (0x0C, "LastName"),
    (0x0D, "HomePhone"),
    (0x0E, "MobilePhone"),
    (0x0F, "EmailAddress"),
    (0x10, "Picture"),
    (0x11, "Status"),
    (0x12, "Data"),
];

/// Code page 17: AirSyncBase.
pub(super) const BASE_TOKENS: &[(u8, &str)] = &[
    (0x05, "BodyPreference"),
    (0x06, "Type"),
    (0x07, "TruncationSize"),
    (0x08, "AllOrNone"),
    (0x0A, "Body"),
    (0x0B, "Data"),
    (0x0C, "EstimatedDataSize"),
    (0x0D, "Truncated"),
    (0x0E, "Attachments"),
    (0x0F, "Attachment"),
    (0x10, "DisplayName"),
    (0x11, "FileReference"),
    (0x12, "Method"),
    (0x13, "ContentId"),
    (0x14, "ContentLocation"),
    (0x15, "IsInline"),
    (0x16, "NativeBodyType"),
    (0x17, "ContentType"),
    (0x18, "Preview"),
    (0x19, "BodyPartPreference"),
    (0x1A, "BodyPart"),
    (0x1B, "Status"),
    (0x1C, "Add"),
    (0x1D, "Delete"),
    (0x1E, "ClientId"),
    (0x1F, "Content"),
    (0x20, "Location"),
    (0x21, "Annotation"),
    (0x22, "Street"),
    (0x23, "City"),
    (0x24, "State"),
    (0x25, "Country"),
    (0x26, "PostalCode"),
    (0x27, "Latitude"),
    (0x28, "Longitude"),
    (0x29, "Accuracy"),
    (0x2A, "Altitude"),
    (0x2B, "AltitudeAccuracy"),
    (0x2C, "LocationUri"),
    (0x2D, "InstanceId"),
];
