//! Outbound mail submission shapes.
//!
//! # The rendered-source seam
//!
//! [`Provider::submit_email_source`](crate::Provider::submit_email_source) sends
//! the caller's **own final MIME bytes** — e.g. a rendered message the host then
//! signed or encrypted — **verbatim**, never re-rendered (contrast
//! [`Provider::submit_email`](crate::Provider::submit_email), which renders a
//! [`Draft`]), and files the Sent copy with **the same bytes** where the
//! transport files it. The receipt's `message_id` is the bytes' own
//! `Message-ID` header — the Write Contract: **stamp the id before submitting**.
//!
//! `recipients` is the envelope. Non-empty, it is the **exact** `RCPT TO` set —
//! where Bcc lives: delivered with no `Bcc` header ever entering the bytes.
//! Empty, the envelope is derived from the bytes' own `To`/`Cc` headers (a
//! `Bcc` header left in the bytes is honored and travels it, visibly); a
//! stripped `Bcc` header omitted from `recipients` is **not** delivered — an
//! explicit choice, never a silent one. `MAIL FROM` is the bytes' `From`.
//!
//! A byte-capable transport (IMAP/SMTP) overrides the verb; one that re-renders
//! from structured fields (JMAP) keeps the rejecting default *even though it
//! advertises [`Capabilities::submission`](crate::Capabilities::submission)* —
//! the capability covers `submit_email`, not the source form (`providers.md`).

use core::fmt;

use engine_core::{
    ids::{MessageIdHeader, ProviderKey},
    mail::EmailAddress,
    scheduling::ScheduleMethod,
};
use serde::{Deserialize, Serialize};

/// A mail message to send.
///
/// The `message_id` is generated by the caller **before** submission (the Write
/// Contract: a stable `Message-ID` precedes the send), so the sent copy can be
/// reconciled by `Message-ID` when it later syncs back (`store-and-sync.md`).
/// The body always carries a plain-text fallback and may add an HTML alternative
/// plus inline or regular attachments. Serializable so a caller can store it as a
/// durable outbox `PendingOp` payload before sending.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Draft {
    /// The pre-generated `Message-ID` header value (no angle brackets).
    pub message_id: MessageIdHeader,
    /// The sender address.
    pub from: EmailAddress,
    /// The recipient addresses.
    pub to: Vec<EmailAddress>,
    /// The `Cc` ("carbon copy") recipients — visible to every recipient. Empty for
    /// none. Defaulted so a payload serialized before Cc/Bcc support still deserializes.
    #[serde(default)]
    pub cc: Vec<EmailAddress>,
    /// The `Bcc` ("blind carbon copy") recipients. They are delivered to (added to the
    /// SMTP envelope) but, by convention, **never** written as a message header, so no
    /// other recipient can see them. Empty for none. Defaulted for back-compat like `cc`.
    #[serde(default)]
    pub bcc: Vec<EmailAddress>,
    /// The subject.
    pub subject: String,
    /// The plain-text body.
    pub text_body: String,
    /// The optional HTML alternative body.
    #[serde(default)]
    pub html_body: Option<String>,
    /// Inline and regular draft attachments.
    #[serde(default)]
    pub attachments: Vec<DraftAttachment>,
    /// An iTIP scheduling object to carry as a **body part** (iMIP, RFC 6047).
    ///
    /// `None` for an ordinary message. Defaulted so a payload serialized before iMIP
    /// support still deserializes. See [`DraftCalendar`] for why this is not an attachment.
    #[serde(default)]
    pub calendar: Option<DraftCalendar>,
    /// The `Message-ID` this message replies to, if any — the RFC 5322 §3.6.4
    /// `In-Reply-To` value (the parent's `Message-ID`, no angle brackets). `None`
    /// for an original (non-reply) message. Defaulted so a payload serialized
    /// before threading support still deserializes.
    #[serde(default)]
    pub in_reply_to: Option<MessageIdHeader>,
    /// The RFC 5322 §3.6.4 `References` chain that threads this message with its
    /// original: the parent's `References` followed by the parent's own
    /// `Message-ID`, oldest first (each value with no angle brackets). Empty for an
    /// original (non-reply) message. Defaulted for back-compat like `in_reply_to`.
    #[serde(default)]
    pub references: Vec<MessageIdHeader>,
}

impl Draft {
    /// Assembles a draft to send.
    ///
    /// The threading linkage defaults to none; set it with the
    /// [`in_reply_to`](Draft::in_reply_to) builder for a reply or forward.
    #[must_use]
    pub fn new(
        message_id: MessageIdHeader,
        from: EmailAddress,
        to: Vec<EmailAddress>,
        subject: impl Into<String>,
        text_body: impl Into<String>,
    ) -> Self {
        Self {
            message_id,
            from,
            to,
            cc: Vec::new(),
            bcc: Vec::new(),
            subject: subject.into(),
            text_body: text_body.into(),
            html_body: None,
            attachments: Vec::new(),
            calendar: None,
            in_reply_to: None,
            references: Vec::new(),
        }
    }

    /// Sets the `Cc` recipients (visible to every recipient).
    #[must_use]
    pub fn with_cc(mut self, cc: Vec<EmailAddress>) -> Self {
        self.cc = cc;
        self
    }

    /// Sets the `Bcc` recipients — delivered via the SMTP envelope but never emitted as
    /// a header, so they stay hidden from every other recipient.
    #[must_use]
    pub fn with_bcc(mut self, bcc: Vec<EmailAddress>) -> Self {
        self.bcc = bcc;
        self
    }

    /// Sets the threading linkage for a **reply**: the `parent` message's `Message-ID`
    /// (the RFC 5322 §3.6.4 `In-Reply-To`) and the full `references` chain (the parent's
    /// `References` plus its own `Message-ID`, oldest first). The assembler emits both so
    /// the sent message threads with its original.
    ///
    /// A forward is not a reply — use [`with_references`](Self::with_references), which
    /// threads it without claiming it answers anything.
    #[must_use]
    pub fn in_reply_to(
        mut self,
        parent: MessageIdHeader,
        references: Vec<MessageIdHeader>,
    ) -> Self {
        self.in_reply_to = Some(parent);
        self.references = references;
        self
    }

    /// Sets the `References` chain (RFC 5322 §3.6.4) **without** an `In-Reply-To` — the
    /// linkage a **forward** carries.
    ///
    /// A forward continues a conversation but does not answer a message, so it takes the
    /// chain and not the reply pointer. That is enough to thread it: RFC 5256 threading,
    /// this engine's own derivation, and every mainstream client all unite on `References`
    /// alone.
    #[must_use]
    pub fn with_references(mut self, references: Vec<MessageIdHeader>) -> Self {
        self.references = references;
        self
    }

    /// Adds an HTML alternative body.
    #[must_use]
    pub fn with_html_body(mut self, html_body: impl Into<String>) -> Self {
        self.html_body = Some(html_body.into());
        self
    }

    /// Clears the HTML alternative body.
    #[must_use]
    pub fn without_html_body(mut self) -> Self {
        self.html_body = None;
        self
    }

    /// Adds an inline or regular attachment.
    #[must_use]
    pub fn with_attachment(mut self, attachment: DraftAttachment) -> Self {
        self.attachments.push(attachment);
        self
    }

    /// Carries an iTIP object as an alternative body part, making this an iMIP message
    /// (RFC 6047) — the way an answer reaches an organizer when the calendar server will
    /// not send it
    /// ([`Capabilities::calendar_scheduling`](crate::Capabilities::calendar_scheduling)).
    #[must_use]
    pub fn with_calendar(mut self, calendar: DraftCalendar) -> Self {
        self.calendar = Some(calendar);
        self
    }
}

/// An iTIP scheduling object carried as an **alternative body part** (iMIP, RFC 6047 §2.4).
///
/// Not a [`DraftAttachment`], and the difference is what makes the message work. An
/// attachment part carries a `Content-Disposition` and a file name — it is a document the
/// message *encloses*. An iTIP object is a **representation of the message itself**: a
/// sibling of the text body inside `multipart/alternative`, whose `Content-Type` carries
/// the `method=` parameter RFC 6047 §2.4 requires and which receiving clients dispatch on.
/// A `DraftAttachment` cannot express that parameter at all, so an answer sent as one is
/// filed as `invite.ics` and never processed as a reply.
///
/// The text body stays load-bearing: RFC 6047 §2.4 says a scheduling message SHOULD carry a
/// human-readable alternative, for the recipients whose client does not understand
/// `text/calendar`. A caller supplies it as [`Draft::text_body`] — "Accepted: Sprint
/// planning" — exactly as for any other message.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct DraftCalendar {
    /// The serialized iCalendar object, `BEGIN:VCALENDAR` … `END:VCALENDAR`.
    pub ical: String,
    /// The scheduling method, which becomes the `method=` `Content-Type` parameter.
    ///
    /// RFC 6047 §2.4 requires it to equal (ignoring case) the `METHOD` property **inside**
    /// `ical`. The assembler emits what it is given rather than re-parsing the object to
    /// check, so a caller that builds the two from one value cannot get them apart; one
    /// that does not, can.
    pub method: ScheduleMethod,
}

impl DraftCalendar {
    /// An iTIP object to carry as a body part, with the `METHOD` it declares.
    #[must_use]
    pub fn new(method: ScheduleMethod, ical: impl Into<String>) -> Self {
        Self {
            ical: ical.into(),
            method,
        }
    }
}

/// A validated `Content-ID` header value without surrounding angle brackets.
///
/// The type keeps inline-image references distinct from arbitrary strings and
/// prevents the characters that would break the header boundary.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(try_from = "String", into = "String")]
pub struct ContentIdHeader(Box<str>);

impl ContentIdHeader {
    /// Builds a content id value without surrounding angle brackets.
    ///
    /// # Errors
    ///
    /// Returns [`ContentIdError`] when the value is empty or contains a character
    /// that cannot be safely placed inside a `Content-ID` header.
    pub fn new(value: impl Into<String>) -> Result<Self, ContentIdError> {
        let value = value.into();
        if value.is_empty() {
            return Err(ContentIdError::Empty);
        }
        if value
            .bytes()
            .any(|b| matches!(b, b'\r' | b'\n' | b'\0' | b'<' | b'>'))
        {
            return Err(ContentIdError::ForbiddenCharacter);
        }
        Ok(Self(value.into_boxed_str()))
    }

    /// Returns the header value without surrounding angle brackets.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl TryFrom<String> for ContentIdHeader {
    type Error = ContentIdError;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        Self::new(value)
    }
}

impl From<ContentIdHeader> for String {
    fn from(value: ContentIdHeader) -> Self {
        value.0.into()
    }
}

impl fmt::Display for ContentIdHeader {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

/// Why a `Content-ID` header value was rejected.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ContentIdError {
    /// The value was empty.
    Empty,
    /// The value contained CR, LF, NUL, `<`, or `>`.
    ForbiddenCharacter,
}

impl fmt::Display for ContentIdError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Empty => f.write_str("content id must not be empty"),
            Self::ForbiddenCharacter => {
                f.write_str("content id contains a forbidden character (CR, LF, NUL, '<', or '>')")
            }
        }
    }
}

impl std::error::Error for ContentIdError {}

/// Whether a draft attachment is a regular attachment or an inline related part.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum DraftAttachmentDisposition {
    /// The part is referenced from the HTML body with a `cid:` URL.
    Inline {
        /// The `Content-ID` value without surrounding angle brackets.
        content_id: ContentIdHeader,
    },
    /// The part should be presented as a regular downloadable attachment.
    Attachment,
}

/// A draft attachment to include in the outbound MIME message.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct DraftAttachment {
    /// The display file name.
    pub file_name: String,
    /// The media type, for example `image/png` or `application/pdf`.
    pub media_type: String,
    /// The attachment bytes.
    pub content: Vec<u8>,
    /// How the part is related to the body.
    pub disposition: DraftAttachmentDisposition,
}

impl DraftAttachment {
    /// Builds an inline attachment referenced by a `cid:` URL in the HTML body.
    #[must_use]
    pub fn inline(
        file_name: impl Into<String>,
        media_type: impl Into<String>,
        content_id: ContentIdHeader,
        content: Vec<u8>,
    ) -> Self {
        Self {
            file_name: file_name.into(),
            media_type: media_type.into(),
            content,
            disposition: DraftAttachmentDisposition::Inline { content_id },
        }
    }

    /// Builds a regular downloadable attachment.
    #[must_use]
    pub fn attachment(
        file_name: impl Into<String>,
        media_type: impl Into<String>,
        content: Vec<u8>,
    ) -> Self {
        Self {
            file_name: file_name.into(),
            media_type: media_type.into(),
            content,
            disposition: DraftAttachmentDisposition::Attachment,
        }
    }

    /// Returns the inline content id, if this is an inline attachment.
    #[must_use]
    pub fn content_id(&self) -> Option<&ContentIdHeader> {
        match &self.disposition {
            DraftAttachmentDisposition::Inline { content_id } => Some(content_id),
            DraftAttachmentDisposition::Attachment => None,
        }
    }

    /// Whether this part is an inline related attachment.
    #[must_use]
    pub fn is_inline(&self) -> bool {
        matches!(self.disposition, DraftAttachmentDisposition::Inline { .. })
    }
}

/// What became of the sender's own copy of a delivered message.
///
/// Delivering and filing are **one step on most transports and two on IMAP**: JMAP files the
/// copy with the submission's `onSuccessUpdateEmail`, Graph and Gmail file it server-side, and
/// an IMAP/SMTP account is delivered over SMTP and then filed by us with a separate `APPEND`.
/// A two-step transport can therefore deliver a message and still fail to file it, and that
/// outcome belongs to the caller: the mail has reached its recipients and must never be
/// re-sent, yet the sender's Sent folder is missing it and no later sync will notice — there
/// is nothing on the server left to reconcile against.
///
/// Every adapter states which of the two it achieved, because a receipt that *cannot* express
/// "delivered but not filed" is what let a lost Sent copy read as a clean send.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SentCopy {
    /// Filed in the account's Sent folder; [`SubmissionReceipt::email_key`] addresses it.
    Filed,
    /// Delivered to its recipients, but the sender's copy was **not** filed.
    Unfiled {
        /// Why filing failed — a failure class and protocol detail, for a log line and a
        /// host-visible hint. Never draft content or addresses.
        detail: String,
    },
}

impl SentCopy {
    /// Whether the sender's copy reached their Sent folder.
    #[must_use]
    pub fn is_filed(&self) -> bool {
        matches!(self, Self::Filed)
    }

    /// Why filing failed, or `None` when it did not fail.
    #[must_use]
    pub fn unfiled_detail(&self) -> Option<&str> {
        match self {
            Self::Filed => None,
            Self::Unfiled { detail } => Some(detail),
        }
    }
}

/// The result of a successful submission — the message reached its recipients.
///
/// Whether the *sender's* copy also reached their Sent folder is a separate question with a
/// separate answer: [`Self::sent_copy`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SubmissionReceipt {
    /// The provider key of the sent message (filed in Sent), for the outbox to
    /// record as the op's resolved key.
    pub email_key: ProviderKey,
    /// The `Message-ID` that was sent, echoed for sync-time reconciliation.
    pub message_id: MessageIdHeader,
    /// What became of the sender's own copy.
    pub sent_copy: SentCopy,
}

impl SubmissionReceipt {
    /// Records a submission whose sent copy **was** filed in the account's Sent folder.
    #[must_use]
    pub fn filed(email_key: ProviderKey, message_id: MessageIdHeader) -> Self {
        Self {
            email_key,
            message_id,
            sent_copy: SentCopy::Filed,
        }
    }

    /// Records a submission that was **delivered but whose sent copy was not filed**, with
    /// `detail` explaining why. The message is still sent: a caller surfaces this, and never
    /// retries the submission.
    #[must_use]
    pub fn unfiled(
        email_key: ProviderKey,
        message_id: MessageIdHeader,
        detail: impl Into<String>,
    ) -> Self {
        Self {
            email_key,
            message_id,
            sent_copy: SentCopy::Unfiled {
                detail: detail.into(),
            },
        }
    }
}

#[cfg(test)]
#[path = "submit_tests.rs"]
mod tests;
