// SPDX-License-Identifier: MPL-2.0
// Ported from mailkit_arkts (user-owned; confirmed 2026-08-12). See ATTRIBUTIONS.md.

/// `ResolveRecipients` (`ResolveRecipients` page-10 token 0x05).
pub const RESOLVE_RECIPIENTS: u8 = 0x05;
/// `Response` (`ResolveRecipients` page-10 token 0x06).
pub const RESPONSE: u8 = 0x06;
/// `Status` (`ResolveRecipients` page-10 token 0x07).
pub const STATUS: u8 = 0x07;
/// `Type` (`ResolveRecipients` page-10 token 0x08).
pub const TYPE: u8 = 0x08;
/// `Recipient` (`ResolveRecipients` page-10 token 0x09).
pub const RECIPIENT: u8 = 0x09;
/// `DisplayName` (`ResolveRecipients` page-10 token 0x0a).
pub const DISPLAY_NAME: u8 = 0x0A;
/// `EmailAddress` (`ResolveRecipients` page-10 token 0x0b).
pub const EMAIL_ADDRESS: u8 = 0x0B;
/// `Certificates` (`ResolveRecipients` page-10 token 0x0c).
pub const CERTIFICATES: u8 = 0x0C;
/// `Certificate` (`ResolveRecipients` page-10 token 0x0d).
pub const CERTIFICATE: u8 = 0x0D;
/// `MiniCertificate` (`ResolveRecipients` page-10 token 0x0e).
pub const MINI_CERTIFICATE: u8 = 0x0E;
/// `Options` (`ResolveRecipients` page-10 token 0x0f).
pub const OPTIONS: u8 = 0x0F;
/// `To` (`ResolveRecipients` page-10 token 0x10).
pub const TO: u8 = 0x10;
/// `CertificateRetrieval` (`ResolveRecipients` page-10 token 0x11).
pub const CERTIFICATE_RETRIEVAL: u8 = 0x11;
/// `RecipientCount` (`ResolveRecipients` page-10 token 0x12).
pub const RECIPIENT_COUNT: u8 = 0x12;
/// `MaxCertificates` (`ResolveRecipients` page-10 token 0x13).
pub const MAX_CERTIFICATES: u8 = 0x13;
/// `MaxAmbiguousRecipients` (`ResolveRecipients` page-10 token 0x14).
pub const MAX_AMBIGUOUS_RECIPIENTS: u8 = 0x14;
/// `CertificateCount` (`ResolveRecipients` page-10 token 0x15).
pub const CERTIFICATE_COUNT: u8 = 0x15;
/// `Availability` (`ResolveRecipients` page-10 token 0x16).
pub const AVAILABILITY: u8 = 0x16;
/// `StartTime` (`ResolveRecipients` page-10 token 0x17).
pub const START_TIME: u8 = 0x17;
/// `EndTime` (`ResolveRecipients` page-10 token 0x18).
pub const END_TIME: u8 = 0x18;
/// `MergedFreeBusy` (`ResolveRecipients` page-10 token 0x19).
pub const MERGED_FREE_BUSY: u8 = 0x19;
/// `Picture` (`ResolveRecipients` page-10 token 0x1a).
pub const PICTURE: u8 = 0x1A;
/// `MaxSize` (`ResolveRecipients` page-10 token 0x1b).
pub const MAX_SIZE: u8 = 0x1B;
/// `Data` (`ResolveRecipients` page-10 token 0x1c).
pub const DATA: u8 = 0x1C;
/// `MaxPictures` (`ResolveRecipients` page-10 token 0x1d).
pub const MAX_PICTURES: u8 = 0x1D;
